# Generated by Django 5.0.7 on 2024-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_adminprofile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='cv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
