# Generated by Django 5.0.7 on 2024-07-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_bank_image_bank_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='url',
            new_name='ihtiyac_url',
        ),
        migrations.AddField(
            model_name='bank',
            name='kobi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='konut_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='tasit_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
