# Generated by Django 5.0.7 on 2024-07-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kredinialblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
